### ISSUE TITLE
Click Compass to open Config

### ISSUE THREAD

**Issue by gucciBane** [fitzchivalrik/compass#1]
First off, wow, this is super cool!

It might be nice to be able to access the config directly from clicking the compass. I would say filtering is the #1 request, but I see that's already on the To-Do list.

Really looking forward to playing with this.

**Comment by fitzchivalrik** [comment]
Thank you for your comment!
The compass has no background/is clickthrough for the cases when it happens to overlap a HUD element which you wanna click (and you are not hiding the compass/there is a missing option).

I tend to have the need for that in my tests more often than not because of my screensize and the location of my compass so I am not sure about making the compass clickable.

I imagine one would not want to open the config that much anyways after setting it all up, would one?

**Comment by gucciBane** [comment]
Yeah, those are fair points. It was a little tedious opening and closing the window during setup, but you're right, you only really do that once.

This is off topic, but do you have any control over the icons that get used? I think it would be amazing if it could be alternatively styled with simple arrows/letters, akin to Fallout 4. I'd be down to help out if you needed it.

**Comment by fitzchivalrik** [comment]
I settled on using the icons from the game directly. In theory, it would be possible to change those.
For now, I have no plans to do that though as I am not sure about the implications yet.
